#ifndef __HEVC_SPEC_H
#define __HEVC_SPEC_H

#define HEVC_PROFILE_MAIN 1
#define HEVC_PROFILE_MAIN_10 2
#define HEVC_PROFILE_MAIN_STILL_PICTURE 3

#define NAL_UNIT_TYPE_CODED_SLICE_TRAIL_N 0
#define NAL_UNIT_TYPE_CODED_SLICE_TRAIL_R 1
#define NAL_UNIT_TYPE_CODED_SLICE_TSA_N 2
#define NAL_UNIT_TYPE_CODED_SLICE_TLA_R 3
#define NAL_UNIT_TYPE_CODED_SLICE_STSA_N 4
#define NAL_UNIT_TYPE_CODED_SLICE_STSA_R 5
#define NAL_UNIT_TYPE_CODED_SLICE_RADL_N 6
#define NAL_UNIT_TYPE_CODED_SLICE_RADL_R 7
#define NAL_UNIT_TYPE_CODED_SLICE_RASL_N 8
#define NAL_UNIT_TYPE_CODED_SLICE_RASL_R 9
#define NAL_UNIT_TYPE_CODED_SLICE_BLA_W_P 16
#define NAL_UNIT_TYPE_CODED_SLICE_BLA_W_RADL 17
#define NAL_UNIT_TYPE_CODED_SLICE_BLA_N_LP 18
#define NAL_UNIT_TYPE_CODED_SLICE_IDR_W_RADL 19
#define NAL_UNIT_TYPE_CODED_SLICE_IDR_N_LP 20
#define NAL_UNIT_TYPE_CODED_SLICE_CRA 21
#define NAL_UNIT_TYPE_VPS 32
#define NAL_UNIT_TYPE_SPS 33
#define NAL_UNIT_TYPE_PPS 34
#define NAL_UNIT_TYPE_AUD 35
#define NAL_UNIT_TYPE_EOS 36
#define NAL_UNIT_TYPE_EOB 37
#define NAL_UNIT_TYPE_FILLER_DATA 38
#define NAL_UNIT_TYPE_PREFIX_SEI 39
#define NAL_UNIT_TYPE_SUFFIX_SEI 40
#define NAL_UNIT_TYPE_INVALID 41

#define SH_SLICE_TYPE_P 0
#define SH_SLICE_TYPE_B 1
#define SH_SLICE_TYPE_I 2
#define SH_SLICE_TYPE_SP 3
#define SH_SLICE_TYPE_SI 4
#define SH_SLICE_TYPE_P_ONLY 5
#define SH_SLICE_TYPE_B_ONLY 6
#define SH_SLICE_TYPE_I_ONLY 7
#define SH_SLICE_TYPE_SP_ONLY 8
#define SH_SLICE_TYPE_SI_ONLY 9

#define HEVC_INTERLACED_TOP_FIELD 3 //SEI -> pic_struct_present_flag -> pic_struct
#define HEVC_INTERLACED_BOTTOM_FIELD 6

#define SAR_NONE 0
#define SAR_1_1     1
#define SAR_12_11 2
#define SAR_10_11 3
#define SAR_16_11 4
#define SAR_40_33 5
#define SAR_24_11 6
#define SAR_20_11 7
#define SAR_32_11 8
#define SAR_80_33 9
#define SAR_18_11 10
#define SAR_15_11 11
#define SAR_64_33 12
#define SAR_160_99 13
#define SAR_R_4_3 14
#define SAR_R_3_2 15
#define SAR_R_2_1 16
#define SAR_Extended 255

#define NALU_HEADER_BYTES 2
#define NALU_HEADER_BITS 16

#define HEVC_ANNEXB_START_CODE_0_BE 0x00000100
#define HEVC_ANNEXB_START_CODE_1_BE 0x00000001

#define HEVC_ANNEXB_START_CODE_0_LE 0x00010000
#define HEVC_ANNEXB_START_CODE_1_LE 0x01000000

#define HEVC_ANNEXB_3TO4BYTES_AND_BE 0xFFFFFF00
#define HEVC_ANNEXB_3TO4BYTES_AND_LE 0x00FFFFFF

#if !defined(_WIN32) && defined(_CPU_BE)
#define HEVC_ANNEXB_START_CODE_0 HEVC_ANNEXB_START_CODE_0_BE
#define HEVC_ANNEXB_START_CODE_1 HEVC_ANNEXB_START_CODE_1_BE
#define HEVC_ANNEXB_3TO4BYTES_AND HEVC_ANNEXB_3TO4BYTES_AND_BE
#else
#define HEVC_ANNEXB_START_CODE_0 HEVC_ANNEXB_START_CODE_0_LE
#define HEVC_ANNEXB_START_CODE_1 HEVC_ANNEXB_START_CODE_1_LE
#define HEVC_ANNEXB_3TO4BYTES_AND HEVC_ANNEXB_3TO4BYTES_AND_LE
#endif

#endif //__HEVC_SPEC_H