#ifndef __ISOM_ERROR_H_
#define __ISOM_ERROR_H_

#include "IsomGlobal.h"

#define ISOM_ERR_OK 0
#define ISOM_ERR_FAIL 1
#define ISOM_ERR_STOP 2
#define ISOM_ERR_SKIP 3

#define ISOM_ERR_COMMON_IO ISOM_FCC('IOER')
#define ISOM_ERR_COMMON_SIZE ISOM_FCC('SIZE')
#define ISOM_ERR_COMMON_SEEK ISOM_FCC('SEEK')
#define ISOM_ERR_COMMON_DATA ISOM_FCC('DATA')
#define ISOM_ERR_COMMON_HEAD ISOM_FCC('HEAD')
#define ISOM_ERR_COMMON_INDEX ISOM_FCC('INDX')
#define ISOM_ERR_COMMON_DEPTH ISOM_FCC('DEPH')
#define ISOM_ERR_COMMON_MEMORY ISOM_FCC('MEMY')

#endif //__ISOM_ERROR_H_