#ifndef __FLV_PARSER_ERR_SPEC_H
#define __FLV_PARSER_ERR_SPEC_H

#define PARSER_FLV_OK 0

#define PARSER_FLV_ERR_UNEXPECTED 0xFFFFFFFF
#define PARSER_FLV_ERR_UNKNOWN 0xFFFFFFFE
#define PARSER_FLV_ERR_HEAD_INVALID (PARSER_FLV_ERR_UNKNOWN - 1)

#define PARSER_FLV_ERR_METADATA_MISS (PARSER_FLV_ERR_HEAD_INVALID - 1)
#define PARSER_FLV_ERR_METADATA_INVALID (PARSER_FLV_ERR_METADATA_MISS - 1)

#define PARSER_FLV_ERR_NON_VIDEO_STREAM (PARSER_FLV_ERR_METADATA_INVALID - 1)
#define PARSER_FLV_ERR_NON_AUDIO_STREAM (PARSER_FLV_ERR_NON_VIDEO_STREAM - 1)

#define PARSER_FLV_ERR_VIDEO_STREAM_UNSUPPORTED (PARSER_FLV_ERR_NON_AUDIO_STREAM - 1)
#define PARSER_FLV_ERR_AUDIO_STREAM_UNSUPPORTED (PARSER_FLV_ERR_VIDEO_STREAM_UNSUPPORTED - 1)
#define PARSER_FLV_ERR_VIDEO_VP6_STREAM_UNSUPPORTED (PARSER_FLV_ERR_VIDEO_STREAM_UNSUPPORTED - 2)
#define PARSER_FLV_ERR_VIDEO_H263_STREAM_UNSUPPORTED (PARSER_FLV_ERR_VIDEO_STREAM_UNSUPPORTED - 3)

#define PARSER_FLV_ERR_NON_KEY_FRAME_INDEX (PARSER_FLV_ERR_UNKNOWN - 100)
#define PARSER_FLV_ERR_NON_MORE_PACKET (PARSER_FLV_ERR_UNKNOWN - 200)

#define PARSER_FLV_ERR_NOT_OPENED (PARSER_FLV_ERR_UNKNOWN - 101)
#define PARSER_FLV_ERR_PARSE_FAILED (PARSER_FLV_ERR_UNKNOWN - 102)
#define PARSER_FLV_ERR_BAD_ALLOC (PARSER_FLV_ERR_UNKNOWN - 103)

#define PARSER_FLV_ERR_IO_READ_FAILED (PARSER_FLV_ERR_UNKNOWN - 201)
#define PARSER_FLV_ERR_IO_SEEK_FAILED (PARSER_FLV_ERR_UNKNOWN - 202)
#define PARSER_FLV_ERR_IO_DATA_INVALID (PARSER_FLV_ERR_UNKNOWN - 203)

#endif //__FLV_PARSER_ERR_SPEC_H