/*
 - FLV Stream Parser (Spec Head) -

 - Author: K.F Yang
 - Date: 2014-11-25
*/

#ifndef __FLV_SPEC_H
#define __FLV_SPEC_H

#define FLV_STREAM_HEAD_SIGN_LE 0x01564C46
#define FLV_STREAM_HEAD_SIGN_BE 0x464C5601

#define FLV_HEAD_LENGTH 9
#define FLV_HEAD_INFO_LENGTH 5

#define FLV_HEAD_HAS_AUDIO_FLAG 4
#define FLV_HEAD_HAS_VIDEO_FLAG 1
#define FLV_HEAD_HAS_AV_FLAG (FLV_HEAD_HAS_AUDIO_FLAG + FLV_HEAD_HAS_VIDEO_FLAG)

#define FLV_TAG_TYPE_AUDIO 0x08
#define FLV_TAG_TYPE_VIDEO 0x09
#define FLV_TAG_TYPE_META 0x12

#define FLV_MP3_AUDIO_TAG_HEAD_LEN 1
#define FLV_AAC_AUDIO_TAG_HEAD_LEN 2
#define FLV_H264_VIDEO_TAG_HEAD_LEN 5

enum FLV_TAG_AUDIO_CODEC
{
	FLV_AUDIO_CODEC_PCM_BE = 0,
	FLV_AUDIO_CODEC_ADPCM,
	FLV_AUDIO_CODEC_MP3, //supported.
	FLV_AUDIO_CODEC_PCM_LE,
	FLV_AUDIO_CODEC_NELLYMOSER_16K,
	FLV_AUDIO_CODEC_NELLYMOSER_8K,
	FLV_AUDIO_CODEC_NELLYMOSER,
	FLV_AUDIO_CODEC_PCM_ALAW,
	FLV_AUDIO_CODEC_PCM_MULAW,
	FLV_AUDIO_CODEC_AAC = 10, //supported.
	FLV_AUDIO_CODEC_SPEEX,
	FLV_AUDIO_CODEC_INVALID
};

enum FLV_TAG_VIDEO_CODEC
{
	FLV_VIDEO_CODEC_H263 = 2,
	FLV_VIDEO_CODEC_SCREEN,
	FLV_VIDEO_CODEC_VP6,
	FLV_VIDEO_CODEC_VP6A,
	FLV_VIDEO_CODEC_SCREEN2,
	FLV_VIDEO_CODEC_H264, //supported.
	FLV_VIDEO_CODEC_REAL_H263,
	FLV_VIDEO_CODEC_MPEG4,
	FLV_VIDEO_CODEC_INVALID
};

enum FLV_TAG_AUDIO_RATE_TYPE
{
	FLV_SAMPLE_RATE_SPECIAL = 0,
	FLV_SAMPLE_RATE_11025HZ,
	FLV_SAMPLE_RATE_22050HZ,
	FLV_SAMPLE_RATE_44100HZ,
	FLV_SAMPLE_RATE_48000HZ
};

enum FLV_TAG_AUDIO_BIT_TYPE
{
	FLV_SAMPLE_SIZE_8BIT = 0,
	FLV_SAMPLE_SIZE_16BIT
};

enum FLV_TAG_AUDIO_CH_TYPE
{
	FLV_CH_MONO = 0,
	FLV_CH_STEREO = 1
};

enum FLV_TAG_VIDEO_FRAME_TYPE
{
	FLV_FRAME_INVALID = 0,
	FLV_FRAME_TYPE_KEY = 1, //AVC (seek Frame.)
	FLV_FRAME_TYPE_INTER = 2, //AVC (non-seek Frame.)
	FLV_FRAME_TYPE_DISP_INTER = 3, //H263 only.
	FLV_FRAME_TYPE_GENERATED_KEY = 4, //reserved for server use only.
	FLV_FRAME_TYPE_VIDEO_INFO_CMD = 5
};

#define FLV_AAC_PACKET_TYPE_HEADER 0
#define FLV_AAC_PACKET_TYPE_RAW 1

#define FLV_AVC_PACKET_TYPE_HEADER 0
#define FLV_AVC_PACKET_TYPE_NALU 1
#define FLV_AVC_PACKET_TYPE_EOS 2

enum FLV_SCRIPT_DATA_TYPE
{
	FLV_AMF_DATA_TYPE_NUMBER = 0,
	FLV_AMF_DATA_TYPE_BOOL,
	FLV_AMF_DATA_TYPE_STRING,
	FLV_AMF_DATA_TYPE_OBJECT,
	FLV_AMF_DATA_TYPE_NULL = 5,
	FLV_AMF_DATA_TYPE_UNDEFINED,
	FLV_AMF_DATA_TYPE_REFERENCE,
	FLV_AMF_DATA_TYPE_ARRAY_MIXED,
	FLV_AMF_DATA_TYPE_OBJECT_END,
	FLV_AMF_DATA_TYPE_ARRAY,
	FLV_AMF_DATA_TYPE_DATE,
	FLV_AMF_DATA_TYPE_LONG_STRING,
	FLV_AMF_DATA_TYPE_INVALID
};

#endif //__FLV_SPEC_H