#ifndef __VFW_HELP_H
#define __VFW_HELP_H

#define _MK_RIFF_FCC(ch4) \
	((((unsigned)(ch4) & 0xFF) << 24) | \
	(((unsigned)(ch4) & 0xFF00) << 8) | \
	(((unsigned)(ch4) & 0xFF0000) >> 8) | \
	(((unsigned)(ch4) & 0xFF000000) >> 24))

enum AVI_VFW_RIFF_TYPES
{
	VFW_RIFF_Others = 0,
	VFW_RIFF_H264,
	VFW_RIFF_H263,
	VFW_RIFF_MPEG4,
	VFW_RIFF_MPEG4V3,
	VFW_RIFF_MPEG4V2,
	VFW_RIFF_MPEG4V1,
	VFW_RIFF_MPG1V,
	VFW_RIFF_MPG2V,
	VFW_RIFF_MJPEG,
	VFW_RIFF_WMV1,
	VFW_RIFF_WMV2,
	VFW_RIFF_WMV3,
	VFW_RIFF_VC1,
	VFW_RIFF_FFV1,
	VFW_RIFF_FLV1,
	VFW_RIFF_THEORA,
	VFW_RIFF_SNOW,
	VFW_RIFF_PRORES,
	VFW_RIFF_DIRAC,
	VFW_RIFF_CAVS,
	VFW_RIFF_AMV
};

AVI_VFW_RIFF_TYPES SearchVFWCodecIdList(unsigned id);

enum WAV_VFW_RIFF_TYPES
{
	VFW_WAV_Others = 0,
	VFW_WAV_PCM,
	VFW_WAV_ADPCM,
	VFW_WAV_FLOAT,
	VFW_WAV_PCM_ALAW,
	VFW_WAV_PCM_MULAW,
	VFW_WAV_GSM_MS,
	VFW_WAV_G723_1,
	VFW_WAV_AMR_NB,
	VFW_WAV_AMR_WB,
	VFW_WAV_WMA1,
	VFW_WAV_WMA2,
	VFW_WAV_WMA3, //Pro
	VFW_WAV_WMA_LOSSLESS,
	VFW_WAV_MP2,
	VFW_WAV_MP3,
	VFW_WAV_AAC,
	VFW_WAV_AAC_ADTS,
	VFW_WAV_AAC_LATM,
	VFW_WAV_AC3,
	VFW_WAV_DTS,
	VFW_WAV_FLAC,
	VFW_WAV_SPEEX
};

WAV_VFW_RIFF_TYPES SearchVFWCodecIdList2(unsigned id);

#endif //__VFW_HELP_H