/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.3-dev-3717-g569a9d3d70"
#endif /* AVUTIL_FFVERSION_H */
