#ifndef _MKV_PARSER_ERROR_SPEC_H
#define _MKV_PARSER_ERROR_SPEC_H

#define PARSER_MKV_OK 0

#define PARSER_MKV_ERR_UNEXPECTED 0xFFFFFFFF
#define PARSER_MKV_ERR_UNKNOWN 0xFFFFFFFE
#define PARSER_MKV_ERR_MEMORY 0xFFFFFFFD
#define PARSER_MKV_ERR_IO 0xFFFFFFFC

#define PARSER_MKV_ERR_OPEN_HEAD_MISSING (PARSER_MKV_ERR_UNEXPECTED - 100)
#define PARSER_MKV_ERR_OPEN_HEAD_FAILED (PARSER_MKV_ERR_OPEN_HEAD_MISSING - 1)
#define PARSER_MKV_ERR_OPEN_SEEK_FAILED (PARSER_MKV_ERR_OPEN_HEAD_FAILED - 1)
#define PARSER_MKV_ERR_OPEN_DOC_INVALID (PARSER_MKV_ERR_OPEN_SEEK_FAILED - 1)
#define PARSER_MKV_ERR_OPEN_DOC_UNSUPPORTED (PARSER_MKV_ERR_OPEN_DOC_INVALID - 1)
#define PARSER_MKV_ERR_OPEN_TIME_UNSUPPORTED (PARSER_MKV_ERR_OPEN_DOC_UNSUPPORTED - 1)
#define PARSER_MKV_ERR_OPEN_TRACK_UNSUPPORTED (PARSER_MKV_ERR_OPEN_TIME_UNSUPPORTED - 1)

#define PARSER_MKV_ERR_READ_END_OF_PACKET (PARSER_MKV_ERR_UNEXPECTED - 200)
#define PARSER_MKV_ERR_READ_FRAME_INVALID (PARSER_MKV_ERR_READ_END_OF_PACKET - 1)
#define PARSER_MKV_ERR_READ_DATA_INVALID (PARSER_MKV_ERR_READ_FRAME_INVALID - 1)
#define PARSER_MKV_ERR_READ_ZLIB_CLOSED (PARSER_MKV_ERR_READ_DATA_INVALID - 1)

#endif //_MKV_PARSER_ERROR_SPEC_H