#ifndef _MATROSKA_SPEC_H
#define _MATROSKA_SPEC_H

#define SUPPORT_EBML_VERSION 1
#define SUPPORT_EBML_ID_LENGTH 4
#define SUPPORT_EBML_SIZE_LENGTH 8

/* EBML */
#define EBML_ID_HEADER 0x1A45DFA3

#define EBML_ID_HEAD_VERSION 0x4286
#define EBML_ID_HEAD_READ_VERSION 0x42F7
#define EBML_ID_HEAD_MAX_ID_LENGTH 0x42F2
#define EBML_ID_HEAD_MAX_SIZE_LENGTH 0x42F3
#define EBML_ID_HEAD_DOC_TYPE 0x4282
#define EBML_ID_HEAD_DOC_TYPE_VERSION 0x4287
#define EBML_ID_HEAD_DOC_TYPE_READ_VERSION 0x4285

#define EBML_ID_GLOBAL_VOID 0xEC
#define EBML_ID_GLOBAL_CRC32 0xBF

/* Matroska */
#define MKV_DOC_TYPE_MAIN "matroska"
#define MKV_DOC_TYPE_WEBM "webm"

#define MKV_BLOCK_LACING_NONE 0
#define MKV_BLOCK_LACING_XIPH 1
#define MKV_BLOCK_LACING_FIXED 2
#define MKV_BLOCK_LACING_EBML 3

#define MKV_TRACK_TYPE_VIDEO 0x01
#define MKV_TRACK_TYPE_AUDIO 0x02
#define MKV_TRACK_TYPE_COMPLEX 0x03
#define MKV_TRACK_TYPE_LOGO 0x10
#define MKV_TRACK_TYPE_SUBTITLE 0x11
#define MKV_TRACK_TYPE_BUTTON 0x12
#define MKV_TRACK_TYPE_CONTROL 0x20

#define MKV_TRACK_ENCODE_SCOPE_ALL_FRAMES 1
#define MKV_TRACK_ENCODE_SCOPE_PRIVATE_DATA 2
#define MKV_TRACK_ENCODE_SCOPE_FULL 3

#define MKV_TRACK_ENCODE_TYPE_COMPRESS 0
#define MKV_TRACK_ENCODE_TYPE_CRYPT 1

#define MKV_TRACK_COMPRESS_TYPE_ZLIB 0
#define MKV_TRACK_COMPRESS_TYPE_BZLIB 1
#define MKV_TRACK_COMPRESS_TYPE_LZO1 2
#define MKV_TRACK_COMPRESS_TYPE_HEAD 3

//Segment Level 0
#define MKV_ID_L0_SEGMENT 0x18538067

//Segment Level 1
#define MKV_ID_L1_SEEKHEAD 0x114D9B74
#define MKV_ID_L1_INFO 0x1549A966
#define MKV_ID_L1_TRACKS 0x1654AE6B
#define MKV_ID_L1_CHAPTERS 0x1043A770
#define MKV_ID_L1_CLUSTER 0x1F43B675
#define MKV_ID_L1_CUES 0x1C53BB6B
#define MKV_ID_L1_ATTACHMENTS 0x1941A469
#define MKV_ID_L1_TAGS 0x1254C367

//SeekHead Level 2 - 3
#define MKV_ID_L2_SEEKHEAD_SEEKENTRY 0x4DBB

#define MKV_ID_L3_SEEKHEAD_SEEKID 0x53AB
#define MKV_ID_L3_SEEKHEAD_SEEKPOS 0x53AC

//Info Level 2
#define MKV_ID_L2_INFO_TIMECODESCALE 0x2AD7B1
#define MKV_ID_L2_INFO_DURATION 0x4489
#define MKV_ID_L2_INFO_TITLE 0x7BA9
#define MKV_ID_L2_INFO_WRITINGAPP 0x5741
#define MKV_ID_L2_INFO_MUXINGAPP 0x4D80
#define MKV_ID_L2_INFO_DATEUTC 0x4461
#define MKV_ID_L2_INFO_SEGMENTUID 0x73A4

//Track Level 2 - 3
#define MKV_ID_L2_TRACK_TRACKENTRY 0xAE

#define MKV_ID_L3_TRACK_TRACKNUMBER 0xD7
#define MKV_ID_L3_TRACK_TRACKUID 0x73C5
#define MKV_ID_L3_TRACK_TRACKTYPE 0x83
#define MKV_ID_L3_TRACK_TRACKVIDEO 0xE0
#define MKV_ID_L3_TRACK_TRACKAUDIO 0xE1
#define MKV_ID_L3_TRACK_TRACKOPERATION 0xE2
#define MKV_ID_L3_TRACK_TRACKCONTENTENCODINGS 0x6D80

#define MKV_ID_L3_TRACK_CODECID 0x86
#define MKV_ID_L3_TRACK_CODECPRIVATE 0x63A2
#define MKV_ID_L3_TRACK_CODECNAME 0x258688
#define MKV_ID_L3_TRACK_CODECDECODEALL 0xAA
#define MKV_ID_L3_TRACK_CODECDELAY 0x56AA
#define MKV_ID_L3_TRACK_SEEKPREROLL 0x56BB

#define MKV_ID_L3_TRACK_TRACKNAME 0x536E
#define MKV_ID_L3_TRACK_TRACKLANGUAGE 0x22B59C
#define MKV_ID_L3_TRACK_TRACKFLAGENABLED 0xB9
#define MKV_ID_L3_TRACK_TRACKFLAGDEFAULT 0x88
#define MKV_ID_L3_TRACK_TRACKFLAGFORCED 0x55AA
#define MKV_ID_L3_TRACK_TRACKFLAGLACING 0x9C
#define MKV_ID_L3_TRACK_TRACKMINCACHE 0x6DE7
#define MKV_ID_L3_TRACK_TRACKMAXCACHE 0x6DF8
#define MKV_ID_L3_TRACK_TRACKDEFAULTDURATION 0x23E383
#define MKV_ID_L3_TRACK_TRACKTIMECODESCALE 0x23314F
#define MKV_ID_L3_TRACK_TRACKMAXBLKADDID 0x55EE

#define MKV_ID_L4_TRACK_TRACKCONTENTENCODING 0x6240

//Audio Track
#define MKV_ID_L4_TRACK_AUDIO_SAMPLINGFREQ 0xB5
#define MKV_ID_L4_TRACK_AUDIO_OUTSAMPLINGFREQ 0x78B5
#define MKV_ID_L4_TRACK_AUDIO_BITDEPTH 0x6264
#define MKV_ID_L4_TRACK_AUDIO_CHANNELS 0x9F

//Video Track
#define MKV_ID_L4_TRACK_VIDEO_FRAMERATE 0x2383E3
#define MKV_ID_L4_TRACK_VIDEO_DISPLAYWIDTH 0x54B0
#define MKV_ID_L4_TRACK_VIDEO_DISPLAYHEIGHT 0x54BA
#define MKV_ID_L4_TRACK_VIDEO_PIXELWIDTH 0xB0
#define MKV_ID_L4_TRACK_VIDEO_PIXELHEIGHT 0xBA
#define MKV_ID_L4_TRACK_VIDEO_PIXELCROPB 0x54AA
#define MKV_ID_L4_TRACK_VIDEO_PIXELCROPT 0x54BB
#define MKV_ID_L4_TRACK_VIDEO_PIXELCROPL 0x54CC
#define MKV_ID_L4_TRACK_VIDEO_PIXELCROPR 0x54DD
#define MKV_ID_L4_TRACK_VIDEO_DISPLAYUNIT 0x54B2
#define MKV_ID_L4_TRACK_VIDEO_FLAGINTERLACED 0x9A
#define MKV_ID_L4_TRACK_VIDEO_STEREOMODE 0x53B8
#define MKV_ID_L4_TRACK_VIDEO_ALPHAMODE 0x53C0
#define MKV_ID_L4_TRACK_VIDEO_ASPECTRATIO 0x54B3
#define MKV_ID_L4_TRACK_VIDEO_COLORSPACE 0x2EB524

//Encoding
#define MKV_ID_L5_TRACK_ENCODINGORDER 0x5031
#define MKV_ID_L5_TRACK_ENCODINGSCOPE 0x5032
#define MKV_ID_L5_TRACK_ENCODINGTYPE 0x5033

#define MKV_ID_L5_TRACK_ENCODINGCOMPRESSION 0x5034
#define MKV_ID_L5_TRACK_ENCODINGENCRYPTION 0x5035

#define MKV_ID_L6_TRACK_ENCODINGCOMPALGO 0x4254
#define MKV_ID_L6_TRACK_ENCODINGCOMPSETTINGS 0x4255

#define MKV_ID_L6_TRACK_ENCODINGENCALGO 0x47E1
#define MKV_ID_L6_TRACK_ENCODINGENCKEYID 0x47E2
#define MKV_ID_L6_TRACK_ENCODINGSIGALGO 0x47E5
#define MKV_ID_L6_TRACK_ENCODINGSIGHASHALGO 0x47E6
#define MKV_ID_L6_TRACK_ENCODINGSIGKEYID 0x47E4
#define MKV_ID_L6_TRACK_ENCODINGSIGNATURE 0x47E3
#define MKV_ID_L6_TRACK_ENCODINGENCAESSETTINGS 0x47E7

//Track Combine-Planes -> MKV_ID_L3_TRACK_TRACKOPERATION
#define MKV_ID_L4_TRACK_COMBINEPLANES 0xE3
#define MKV_ID_L5_TRACK_PLANE 0xE4
#define MKV_ID_L6_TRACK_PLANEUID 0xE5
#define MKV_ID_L6_TRACK_PLANETYPE 0xE6

//Chapters Level 2 - 3
#define MKV_ID_L2_CHAPTERS_EDITIONENTRY 0x45B9

#define MKV_ID_L3_CHAPTERS_EDITIONUID 0x45BC
#define MKV_ID_L3_CHAPTERS_EDITIONFLAGHIDDEN 0x45BD
#define MKV_ID_L3_CHAPTERS_EDITIONFLAGDEFAULT 0x45DB
#define MKV_ID_L3_CHAPTERS_EDITIONFLAGORDERED 0x45DD

#define MKV_ID_L3_CHAPTERS_CHAPTERATOM 0xB6

#define MKV_ID_L4_CHAPTERS_CHAPTERTIMESTART 0x91
#define MKV_ID_L4_CHAPTERS_CHAPTERTIMEEND 0x92
#define MKV_ID_L4_CHAPTERS_CHAPTERUID 0x73C4
#define MKV_ID_L4_CHAPTERS_CHAPTERFLAGHIDDEN 0x98
#define MKV_ID_L4_CHAPTERS_CHAPTERFLAGENABLED 0x4598
#define MKV_ID_L4_CHAPTERS_CHAPTERPHYSEQUIV 0x63C3

#define MKV_ID_L4_CHAPTERS_CHAPTERDISPLAY 0x80

#define MKV_ID_L5_CHAPTERS_CHAPSTRING 0x85
#define MKV_ID_L5_CHAPTERS_CHAPLANG 0x437C

//Cluster Level 2 - 3
#define MKV_ID_L2_CLUSTER_CLUSTERTIMECODE 0xE7
#define MKV_ID_L2_CLUSTER_CLUSTERPOSITION 0xA7
#define MKV_ID_L2_CLUSTER_CLUSTERPREVSIZE 0xAB

#define MKV_ID_L2_CLUSTER_SIMPLEBLOCK 0xA3 //v2
#define MKV_ID_L2_CLUSTER_BLOCKGROUP 0xA0

#define MKV_ID_L3_CLUSTER_BLOCKGROUP_BLOCK 0xA1
#define MKV_ID_L3_CLUSTER_BLOCKGROUP_BLOCKDURATION 0x9B
#define MKV_ID_L3_CLUSTER_BLOCKGROUP_BLOCKREFERENCE 0xFB
#define MKV_ID_L3_CLUSTER_BLOCKGROUP_CODECSTATE 0xA4
#define MKV_ID_L3_CLUSTER_BLOCKGROUP_DISCARDPADDING 0x75A2

#define MKV_ID_L3_CLUSTER_BLOCKGROUP_BLOCKADDITIONS 0x75A1
#define MKV_ID_L4_CLUSTER_BLOCKGROUP_BLOCKMORE 0xA6
#define MKV_ID_L5_CLUSTER_BLOCKGROUP_BLOCKADDID 0xEE
#define MKV_ID_L5_CLUSTER_BLOCKGROUP_BLOCKADDITIONAL 0xA5

//Cues Level 2 - 3
#define MKV_ID_L2_CUES_POINTENTRY 0xBB

#define MKV_ID_L3_CUES_POINT_CUETIME 0xB3
#define MKV_ID_L3_CUES_POINT_CUETRACKPOSITION 0xB7

#define MKV_ID_L4_CUES_POINT_POS_CUETRACK 0xF7
#define MKV_ID_L4_CUES_POINT_POS_CUECLUSTERPOSITION 0xF1
#define MKV_ID_L4_CUES_POINT_POS_CUERELATIVEPOSITION 0xF0
#define MKV_ID_L4_CUES_POINT_POS_CUEDURATION 0xB2
#define MKV_ID_L4_CUES_POINT_POS_CUEBLOCKNUMBER 0x5378

//Attachments Level 2 - 3
#define MKV_ID_L2_ATTACHMENTS_ATTACHEDFILE 0x61A7

#define MKV_ID_L3_ATTACHMENTS_FILEDESC 0x467E
#define MKV_ID_L3_ATTACHMENTS_FILENAME 0x466E
#define MKV_ID_L3_ATTACHMENTS_FILEMIMETYPE 0x4660
#define MKV_ID_L3_ATTACHMENTS_FILEDATA 0x465C
#define MKV_ID_L3_ATTACHMENTS_FILEUID 0x46AE

//Tags Level 2 - 3
#define MKV_ID_L2_TAGS_TAG 0x7373

#define MKV_ID_L3_TAGS_SIMPLETAG 0x67C8
#define MKV_ID_L3_TAGS_TAGTARGETS 0x63C0

#define MKV_ID_L4_TAGS_TAGNAME 0x45A3
#define MKV_ID_L4_TAGS_TAGSTRING 0x4487
#define MKV_ID_L4_TAGS_TAGLANG 0x447A

#define MKV_ID_L4_TAGS_TAGTARGETS_TYPE 0x63CA
#define MKV_ID_L4_TAGS_TAGTARGETS_TYPEVALUE 0x68CA
#define MKV_ID_L4_TAGS_TAGTARGETS_TRACKUID 0x63C5
#define MKV_ID_L4_TAGS_TAGTARGETS_CHAPTERUID 0x63C4
#define MKV_ID_L4_TAGS_TAGTARGETS_ATTACHUID 0x63C6

#endif //_MATROSKA_SPEC_H