#ifndef _MATROSKA_INTERNAL_ERROR_H
#define _MATROSKA_INTERNAL_ERROR_H

typedef unsigned __MKV_ERR_TYPE__;

#ifndef _MAKE_MKV_ERR
#define _MAKE_MKV_ERR(ch4) \
	((((__MKV_ERR_TYPE__)(ch4) & 0xFF) << 24) | \
	(((__MKV_ERR_TYPE__)(ch4) & 0xFF00) << 8) | \
	(((__MKV_ERR_TYPE__)(ch4) & 0xFF0000) >> 8) | \
	(((__MKV_ERR_TYPE__)(ch4) & 0xFF000000) >> 24))
#endif

#define MKV_ERR_OK 0
#define MKV_ERR_FAIL 1

#define MKV_ERR_INVALID_IO _MAKE_MKV_ERR('IOER')
#define MKV_ERR_INVALID_SIZE _MAKE_MKV_ERR('SIZE')
#define MKV_ERR_INVALID_HEAD _MAKE_MKV_ERR('HEAD')
#define MKV_ERR_INVALID_DATA _MAKE_MKV_ERR('DATA')
#define MKV_ERR_INVALID_BLOCK _MAKE_MKV_ERR('BLCK')
#define MKV_ERR_INVALID_CLUSTER _MAKE_MKV_ERR('CLUS')

#define MKV_ERR_PARSE_SEEKHEAD _MAKE_MKV_ERR('PSHE')
#define MKV_ERR_PARSE_INFO _MAKE_MKV_ERR('PINF')
#define MKV_ERR_PARSE_TRACKS _MAKE_MKV_ERR('PTCK')
#define MKV_ERR_PARSE_CHAPTERS _MAKE_MKV_ERR('PCHP')
#define MKV_ERR_PARSE_CUES _MAKE_MKV_ERR('PCUE')
#define MKV_ERR_PARSE_CLUSTER _MAKE_MKV_ERR('PCLU')
#define MKV_ERR_PARSE_FILES _MAKE_MKV_ERR('PACH')
#define MKV_ERR_PARSE_TAGS _MAKE_MKV_ERR('PTAG')

#define BREAK_AND_SET_RESULT(x,result) \
	{(x) = (result); break;}

#endif //_MATROSKA_INTERNAL_ERROR_H